version: "3.8"

services:
  redis:
    container_name: redis
    image: redis:7.0

  redis-ui: # to have a visual UI to manage redis cache
    container_name: redis-ui
    image: redislabs/redisinsight:1.14.0
    ports:
      - 8001:8001
    depends_on:
      - redis

  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  api:
    build: .
    command: "uvicorn src.app:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    depends_on:
      - redis
      - db
